version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "MikuroXina"
    target-branch: main
    commit-message:
      prefix: chore(npm)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "MikuroXina"
    target-branch: main
    commit-message:
      prefix: chore(ci)
