version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "MikuroXina"
      - "shun-shobon"
    target-branch: main
    commit-message:
      prefix: build(deps)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "MikuroXina"
    target-branch: main
    commit-message:
      prefix: ci
